// Code generated by "stringer -type TagType"; DO NOT EDIT.

package sframe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Tag-1]
	_ = x[TagVardef-2]
	_ = x[TagNumeric-3]
	_ = x[TagPair-4]
	_ = x[TagPath-5]
	_ = x[TagTransform-6]
	_ = x[TagString-7]
	_ = x[Spark-8]
	_ = x[SparkBuiltin-9]
	_ = x[SparkMacro-10]
	_ = x[SparkExpr-11]
	_ = x[SparkText-12]
	_ = x[TagArray-128]
}

const (
	_TagType_name_0 = "UndefinedTagTagVardefTagNumericTagPairTagPathTagTransformTagStringSparkSparkBuiltinSparkMacroSparkExprSparkText"
	_TagType_name_1 = "TagArray"
)

var (
	_TagType_index_0 = [...]uint8{0, 9, 12, 21, 31, 38, 45, 57, 66, 71, 83, 93, 102, 111}
)

func (i TagType) String() string {
	switch {
	case i <= 12:
		return _TagType_name_0[_TagType_index_0[i]:_TagType_index_0[i+1]]
	case i == 128:
		return _TagType_name_1
	default:
		return "TagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
